#!/bin/bash
foldername=$(date +%Y_%m_%d_%H_%M_%S)
mkdir $foldername
cat /etc/passwd >> $foldername/user_list
cat /etc/group >> $foldername/group_list
iptables -L >> $foldername/firewall
netstat >> $foldername/uslugi
ps >> $foldername/procesy
